name: exercise

on:
  push:
    branches:
      - "main"

jobs:
  different-check:
    strategy:
      matrix:
        platform: [windows-latest,ubuntu-latest]
    runs-on: ${{ matrix.platform }}
    steps:
    - name: Check Node code
      uses: actions/checkout@v2
    - name: Setup node
      uses: actions/setup-node@v2
      with:
         node-version: '14'
  registry:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@main
      - name: Build and push to dockerhub
        uses: docker/build-push-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
          dockerfile: dockerfile
          repository: ${{ github.repository }}
          tag_with_ref: true
          tags: ${{ github.sha }}
    